apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: upper
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: springdeveloper/upper:0.0.1
